'use strict'

const assert = require('assert')
const {decrypt} = require('../app/decryption')

let testCases = [
    {
        encryptedText: 'BRUKRTLHZVSIACHETMFMXBLHKGDXTVLXQXALNRWGVVQIMIVBGJGKFELBHRSLHTHHLIVMHMFYHVETMMGGXRUKRTLXWJGKLXGKTKWHKXJTGWEBLWAHGTDTBRLXQXMLNEDERQWTGWMGXRUKRTLXWMFYHVETMMGGIIFWBRYBGTMMBRLHVVQIMSYKTTZBVEDZHVAMAQKNLYSEECWGVVQIMMGGTPYHKMLAFWUEXEJMXBLNLYSEECJXYIJLMSVTMELATXALMVSGLQAMMIVHKWLHKIVNGIFVKCHMXHAGMLWVEISK',
        key: 'TEST',
        plainText: 'INCRYPTOGRAPHYPLAINTEXTORCLEARTEXTISUNENCRYPTEDINFORMATIONASOPPOSEDTOINFORMATIONENCRYPTEDFORSTORAGEORTRANSMISSIONPLAINTEXTUSUALLYMEANSUNENCRYPTEDINFORMATIONPENDINGINPUTINTOCRYPTOGRAPHICALGORITHMSUSUALLYENCRYPTIONALGORITHMSCLEARTEXTUSUALLYREFERSTODATATHATISTRANSMITTEDORSTOREDUNENCRYPTEDINTHECLEAR'
    }
]

describe('Decrypt', function () {
    describe('Decrypt String', function () {
        testCases.forEach(function (testCase) {
            it('should return decrypted string', function () {
                assert.deepStrictEqual(decrypt(testCase.encryptedText, testCase.key), testCase.plainText)
            })
        })
    })
})
