'use strict'

const assert = require('assert')
const {encrypt} = require('../app/encryption')

let testCases = [
    {
        plainText: 'INCRYPTOGRAPHYPLAINTEXTORCLEARTEXTISUNENCRYPTEDINFORMATIONASOPPOSEDTOINFORMATIONENCRYPTEDFORSTORAGEORTRANSMISSIONPLAINTEXTUSUALLYMEANSUNENCRYPTEDINFORMATIONPENDINGINPUTINTOCRYPTOGRAPHICALGORITHMSUSUALLYENCRYPTIONALGORITHMSCLEARTEXTUSUALLYREFERSTODATATHATISTRANSMITTEDORSTOREDUNENCRYPTEDINTHECLEAR',
        encryptedText: 'BRUKRTLHZVSIACHETMFMXBLHKGDXTVLXQXALNRWGVVQIMIVBGJGKFELBHRSLHTHHLIVMHMFYHVETMMGGXRUKRTLXWJGKLXGKTKWHKXJTGWEBLWAHGTDTBRLXQXMLNEDERQWTGWMGXRUKRTLXWMFYHVETMMGGIIFWBRYBGTMMBRLHVVQIMSYKTTZBVEDZHVAMAQKNLYSEECWGVVQIMMGGTPYHKMLAFWUEXEJMXBLNLYSEECJXYIJLMSVTMELATXALMVSGLQAMMIVHKWLHKIVNGIFVKCHMXHAGMLWVEISK',
        key: 'TEST'
    }
]

describe('Encrypt', function () {
    describe('Encrypt String', function () {
        testCases.forEach(function (testCase) {
            it('should return encrypted string', function () {
                assert.deepStrictEqual(encrypt(testCase.plainText, testCase.key), testCase.encryptedText)
            })
        })
    })
})
